name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      VITE_BASE_URL: ${{ secrets.VITE_BASE_URL }}
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Create .env file
      run: |
        echo "VITE_BASE_URL=${{ secrets.VITE_BASE_URL }}" > .env

    - name: Set up Docker Compose
      run: |
        curl -L "https://github.com/docker/compose/releases/download/v2.23.0/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
        chmod +x /usr/local/bin/docker-compose
        docker-compose --version

    - name: Set up .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '9'

    - name: Build .NET API
      run: dotnet build ./TheMerkleTrees/TheMerkleTrees.Api --configuration Release

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'

    - name: Install dependencies
      run: npm install
      working-directory: ./TheMerkleTreesClient

    - name: Build Nuxt app
      run: npm run build
      working-directory: ./TheMerkleTreesClient

    - name: Start MongoDB
      uses: supercharge/mongodb-github-action@1.6.0
      with:
        mongodb-version: '4.4'

    - name: Start IPFS
      run: docker-compose up -d ipfs

    - name: Install Promtool
      run: |
        wget https://github.com/prometheus/prometheus/releases/download/v2.43.0/prometheus-2.43.0.linux-amd64.tar.gz
        tar xvfz prometheus-*.tar.gz
        sudo mv prometheus-*/promtool /usr/local/bin/
        promtool --version

    - name: Check Prometheus config
      run: promtool check config ./prometheus.yml

